# Generated by Django 5.1.7 on 2025-04-05 13:07

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comments_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasolineOwada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular_gas', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^\\d{3}$', message='3桁の数字')])),
                ('deisel_gas', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^\\d{3}$', message='3桁の数字')])),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
