# Generated by Django 5.1.7 on 2025-04-05 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_gasolineowada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasolineowada',
            name='deisel_gas',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{3}$', message='3桁の数字')]),
        ),
        migrations.AlterField(
            model_name='gasolineowada',
            name='regular_gas',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{3}$', message='3桁の数字')]),
        ),
    ]
