# Generated by Django 5.1.7 on 2025-04-05 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_gasolineowada_deisel_gas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasolineowada',
            old_name='deisel_gas',
            new_name='deisel',
        ),
        migrations.RenameField(
            model_name='gasolineowada',
            old_name='regular_gas',
            new_name='regular',
        ),
    ]
