# Generated by Django 5.1.7 on 2025-04-05 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_deisel_gas_gasolineowada_deisel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasolineowada',
            name='deisel',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{3}$', message='3桁の数字')], verbose_name='軽油'),
        ),
        migrations.AlterField(
            model_name='gasolineowada',
            name='regular',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{3}$', message='3桁の数字')], verbose_name='レギュラー'),
        ),
    ]
