# Generated by Django 5.1.7 on 2025-04-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_comments_good_comments_image_post_good'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='good',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='評価'),
        ),
    ]
