# Generated by Django 5.1.7 on 2025-04-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_poisute_category_poisute_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poisute',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
