# Generated by Django 5.1.7 on 2025-04-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_poisute_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poisute',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='poisute_img/'),
        ),
    ]
