# Generated by Django 5.1.7 on 2025-05-11 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poopgame', '0002_unppointhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('add', '足し算'), ('sub', '引き算'), ('mul', '掛け算')], max_length=4)),
                ('operand_a', models.PositiveSmallIntegerField()),
                ('operand_b', models.PositiveSmallIntegerField()),
                ('user_answer', models.IntegerField(blank=True, null=True)),
                ('correct_answer', models.IntegerField()),
                ('is_correct', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
