# Generated by Django 5.1.7 on 2025-05-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poopgame', '0003_attemptlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='お手伝い内容')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='獲得ポイント')),
            ],
        ),
    ]
