# Generated by Django 5.1.7 on 2025-04-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomimon', '0004_alter_map_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='category',
            field=models.CharField(blank=True, choices=[('can', '空き缶'), ('bottle', 'ペットボトル'), ('glass', 'ビン'), ('snack', 'お菓子の袋'), ('other', 'その他')], max_length=100, null=True),
        ),
    ]
