# Generated by Django 5.1.7 on 2025-04-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomimon', '0007_usergomimon'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergomimon',
            name='gomimon_atack',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usergomimon',
            name='gomimon_defence',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usergomimon',
            name='gomimon_element',
            field=models.CharField(default='ノーマル', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usergomimon',
            name='gomimon_exp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usergomimon',
            name='gomimon_hp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usergomimon',
            name='gomimon_level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usergomimon',
            name='gomimon_maxhp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usergomimon',
            name='gomimon_skill',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
