# Generated by Django 5.1.7 on 2025-04-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomimon', '0008_usergomimon_gomimon_atack_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gomimon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='gomimon_images/')),
                ('gomimon_type', models.CharField(choices=[('burnable', '燃えるゴミ'), ('nonburnable', '燃えないゴミ'), ('can', '資源ごみ（缶）'), ('pet', '資源ごみ（ペット）')], max_length=20)),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('skill', models.CharField(max_length=100)),
                ('skill_effect', models.TextField(blank=True)),
            ],
        ),
    ]
