# Generated by Django 5.1.7 on 2025-04-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomimon', '0009_gomimon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gomimon',
            name='gomimon_type',
            field=models.CharField(choices=[('burnable', '燃えるゴミ'), ('nonburnable', '燃えないゴミ'), ('can', '資源ごみ（缶）'), ('pet', '資源ごみ（ペット）'), ('bin', '資源ごみ（びん）'), ('plastic', 'プラスチック'), ('paper', '資源ごみ（紙類）'), ('big', '粗大ゴミ'), ('toxic', '有害ゴミ')], max_length=20),
        ),
    ]
