# Generated by Django 5.1.7 on 2025-04-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomimon', '0012_alter_gomimon_gomimon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='good',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='picking',
            field=models.CharField(blank=True, choices=[('picked', '回収済み'), ('not_picked', '未回収')], max_length=10, null=True),
        ),
    ]
