# Generated by Django 5.1.7 on 2025-05-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomimon', '0013_map_good_map_picking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='good',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='image',
            field=models.ImageField(null=True, upload_to='poisute_img/'),
        ),
        migrations.AlterField(
            model_name='map',
            name='picking',
            field=models.CharField(choices=[('picked', '回収済み'), ('not_picked', '未回収')], max_length=10, null=True),
        ),
    ]
